apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-ground
  namespace: three-tier
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGJobWlkZm9k
  CLOUDINARY_KEY: NjcxNDI0Nzc5ODQyODI0
  CLOUDINARY_SECRET: cG1WYVNYOFJtck0tdnYtVVJ1d2tRdHI4MmR3
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lZMmhoYm1GcmVXRTVNVEVpTENKaElqb2lZMjAxTm1Oa2FHa3dNekp2ZHpKcGMyWnFjWEF4YzJaNk9DSjkuRE5kTGZlUGZoYXU1bm41RXpIT1REUQ==
  DB_URL: bW9uZ29kYitzcnY6Ly9yYXZpdGVqYTpkYXRhMTIzQDMtdGllci1kZXBsb3ltZW50LmZ4cnJlLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT0zLVRpZXItRGVwbG95bWVudA==
  SECRET: cmF2aXRlamE=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: sriram8788/campground:replaceImageTag
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-ground
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-ground
                  key: CLOUDINARY_KEY
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-ground
                  key: CLOUDINARY_SECRET
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-ground
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-ground
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-ground
                  key: SECRET
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
