---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: yelp-camp-ground
  namespace: three-tier
spec:
  encryptedData:
    CLOUDINARY_CLOUD_NAME: AgCr4sb+yzKMa7KLzgPHnhHnBiEtHZ54oJwz5GzkNXPbp3ft4OvIZZIF1G9F3bM1aIA8FlEYgPsNSBP4AI9iuiQoz/OizDlvm0SEPicPLhxGeRcSP1IGizXMt0E8sZQlZbzlQoGVBRvHCsnInQNZ1BBFjHLIxulsQ9xBNiUfTvTLbpsjR6KT5sh//U9GYAx+XDjQBtOiiKnFWgwB3UqRnxGLKd8xeCB0M0ESDa39w5wJ91KTrN8oPAx8gDPXpMglUR4eT1WX4CcVkUfs8MFeCZrg/eeOBD9olaebVVwYuwCH/rSM08BNk5giCzCdOsLJa/+r+WizPIlUaNVvQ7Vs9sAsLH4LU00hX5EHO/fKqt0JN5J/FrLOl1BjtGb11Vo3A+cpa1dy7RmBKNpO8Xxp10Gz+AdoR80Pk3a8TFvuHhpe5/SyNP+BEf3flVS9oAE1xLJjgXWnAWP4p1JeNy1J6LeNedfTs/O46TRtEZkyH+mdHkOuox/VAw/oGcWjluDIf380RDyqZ1IY25ymqYbINtxtOUjKLR5dBCHM9zoVHkaXhJKxJ8llWgwul1U180hbktAgHf+zv/Dlv+XbjqRi9yGVe3c7Gx4x9uNHpA6gwHqaGkxQiHDEvp9j4orHv7IKjO7akrM2ZbA8iOFtUlBi17h41fyy+NFYW6GzGtDC9k78ARlYWw3ERNcH2vU0KJsnQ6sQbGscL/Ep0uk=
    CLOUDINARY_KEY: AgAmQvt6M7HwPMj3r02NJuq1eFKsoQ5nVJAPkJaEBvhajdcPUGJ1yvhxrWN/KlUTCE9GTBKB8mq8rQI1FCmBPDpM5eMcMODciSxEjt4c1OO19WZ/uRUsEBIP33Q3apUCaS9PCSuLMp/dMuIwFIRBnF8uP/bGIWoe7xbQV3JfuRJgNVCx0qWSsTrN7vTUn44SwLAJnK61Ecv+KNjZs6XAEZ/SLzlCWNF931Y7zeoXfsJRG+8VSAEcJmYRNAKzju39juWoTSDhk5oFrKwnC1DWueN3+vs+948GhKpgRT8JKiEiGD6Pbkuim6efoM/f+Rr6tM1zQjyudfGImXmEvGrHIaMcgmDDIgCbVmDnwXKH4lN6zlfE6j0Kf7mP44VswWrqyS6eEfGDxL4I0+kJlabKXjCIrsluX8cydswDe22Jbsh7Vh9dfEPIWvZm6dRVIXFIDuutn49pf6Bh6hf2B00/AOU9Mar8x8jeVNnglFT1589YgCwubARctnprtxaGkEz453TpVn/vDYUXAYdIgckL6RpVbWj/iq9vZvbbzQ1WgzXopxwWxhIo1zg/y86LCMSmUWQ0LUS7y7QFraelqqY6ap1XuAdUEaVsS7Xv37nqz1FVNEuVgMM8TpswoHqfzEhlJHIQRAuFuV+2H2CrJuVZxT2I0DsyNJ+WwxeRrGBV/fR1tw/vOCerNZf5iMWXcD9WMOjms8tq9CdpKRNFcryy0l4=
    CLOUDINARY_SECRET: AgCMWIi3Cds9lIRw7VrzRRHZX9Wm9ZjlpO31DPGTAuLuKUdG1yjQ59cB6nDB4ibj63kLVrvJW2uPJsova+skSAj1Zh8deqZaRzqSa+haIQBUVGslWi5L61z00u5Vd8ZZiFAD8x6DVoAvUA4MqwZEBt5Hb6Hit4OzKjZCt9zzwh4eiNHMacjmpNS1paAA4iYrkuUhYKQQW66Loyurd2tzHQokynZVQJpNz0ZG7m0qd3A1PspMidr6K7vQaPrM6MjivwKM2C1jqh6FPK3240wwfetF5Jd9lKYu20M0e68LDsX3MfAgJxl9ojgViUX7teF9NtnnlNP27LzdnhgvJuIaxIHqZTLNav7J+paLETzP79pPlFRZf0kPSAhSAk3ys8nqoKLSmhTrQ4Z7qr9LdbmEGtV8HZp9HFpHlehopbmlD8cHyw7lke30UEpQ3WTLm15sg2Nt06eK+YDNlqGAk20JZx7gkNyWMAlNDj3Sxyp0DDp4ROTAoco3lQRXErzXrcS3vUgLSPEED6LceZwWGN3Gtfx9HcS037RBQYaTK5VFDQ4onRT0V6uwnI7HbUXmjLOD3HPHb7RejiZ4HmdQa4GNgS5I4waIxe/7Qp3C5KWXwVNJ/shGAO3AEowe5n3ksuqvp/BKG8cfaDJAaeO9Qd2O6/Q0pzhIZkzVfWLZScji+0n688T0pOS2QgBEvVJQumLUuk0M0sMLQsuT94VMTOBzwCrCMzeJd3AEpfGU36o=
    DB_URL: AgCGxpX2bltE8Xd+pqI9Q9YmqTptaYFFN6nqyqx99UP0Yv6tojxE3JTH5h+5IJwcVsB+YpnD6HGCr+2OVRRqRQrFOOQLx+tItgPTZVqmkgOSlBVDQXzuRSjWjlm2CfgBFDzE3oEMsUtFzsDt/d62rYjGbNuDajtXCG029XVXYV7PrNjId5uqQ3flp0ZwzKaM8soK4kSXmph2oz1GGu/65uMuNQgqKLge3xt6U+5uhJX91gb+HCdmZhToJJ2kB8VvVVsarij71DAHK+mAV4dPVF48MjxPZ7FVZbM9R5jQ3pDSUUACUxottz9mY+6/xAmtvfHssHD2piQ8TB4uZmyn3TvhZe5lo5nohvzIbv81DM3h9brzWyksxwdBwL5VffkwWZpU2fWFYwaT9xgc9IAf9fvpeHgBMvCu9veXmKAypV3s2Rio+crEbF51QnoprRHLOevWNGsTMOIrC3HtUvXzT/lELyP8ecuMxJoh8WElHmThpORnXzyxpiLCreMGechLffuoSkrFOzMtOND9JPmSxq0f4r5lEX0RQZJ9EtjbLzbpMMkGtuxFECNM/AeU7Us/c0XVuom+Vqxi5Xw+DqLIERKMRAcTjPTmOBv/L1jXiyoJzuoJ7H8fIujjs4gkhwD2MSFvTTW/VT36SnPPhJfk/khnkjTTKNxmWv4dNGQRCgltmezcPXoYa8aw/Hbe0elk/Wgwu60SqeuwANJAXnoOR2CRQs8sT4XvjzgohucQPl1hABlz7/ns3ZuGJb3C3u2MMTX3oVKlZYdNv+ov/evO2ySQtHLIIY+2hFR9zQiWnQCG6+J5GlpkqDEuI7TX/xdH7YlAvj4qieDT2Tnao2St0aJJBxOSdyBD01/Q
    MAPBOX_TOKEN: AgACceTXaPzQ8llNi3jLciqvHEfkajB3y+UNqjRZTZt5zfu6pBnDT1rkv2WRjSK7yM7XVoCm4Ju5XxKokMLUQA3e9asrpvI0hxS95qQ1l8Nz9jBdRVX4FcUBCThorvj0VP/zdhbsTPVSO1oYYlhc9VnkfnhOWYOnHYKxUOQl7e/t+LujyPnGHvfgILSRrwgvTAeVbhbvYFkpFW+o3YFZPN2xsQXUx8E7qb8dDx3/Q73A9dLwHFo9O0kx4zObsp7ZHK3e5YrnzFWVbK+fnXTbqQS68vi0IBQCNs95K+u2iQXT4z5igJl9ty0j3DwfqxB8KlkPrFhDJopFp/HTSVgSbdwGBIhaLemMXQpOFs56AJ23Pr/mmwHoyw9USRXat5f5rZ8eHbuLNV/kpaFSeYl7DwSAtjdfM9bjOijUxd3fTbpesQNlmPL5oNlNs2t1vruBVsx++uk+1vROCBjrwfS6yJpV0njelaQ8nlxrpT5gtT9WNPbDxSohIPEz39U6Goss7CNCtpP8SZlhtoeez3yHW/3oELCwcDaGbUqPvSFgWWR3i2xZar4hxHPYogx6TMzCWg2+/UgKHKRG1HXtRR8o7lKFh42oLPDWXZsL9tcafZv2uB8olAkKfeH3zYSf+YKztS0Ie8wf6hKaiU2zyKp5Ag/yV8noQno+gb05kUmGsee4/FtczVw50N8npM9p3hBAkvy+1no59YenKirxpCO4t54etnoOGw5O/2vSsFoDKgVz7WqOMovQHKl+QcVlSQLasqRzDHdDX/O4G0GJsJY72+LJE2zkRLrYeSKpJ30GnoFY3fyqWV51Wrxqyhu/u6Bv
    SECRET: AgALTvK/Dr1XZiaVGZJwqzRPLtp31p8nsSs4mD4E1c5dDLd+seiFXngaiRKY3hyFu/t0e9AfJLArUGC/3yQ+p38klGexPR9TGCPM1w70zGbSvPkKhcs8YPuomGY8gyBx1q859gfx77z2WiTYegkc/BTig0kvKx3VXcc1h+ValzIbmXi6lejU8GOqFvyO1g5lzS99GurDP/1lV4Le0ovhWjb5fZuog2AgMAT/nJUYfxztI9o/RQV2+90+Ojs1nBlMtTyOOO0AMY5NKgMMcg/S1gFD39zOfyPD5A37uNxDGfOW0nwFdlVjWzz3jKye1Wzb0QF7n4D5nTbLEv72WYZ7cRfJeacNC5XXyFNrqJv5xndzaHkUemnRW+joGTrk5LeZEklTXutgwxgqOC+RFR5iznUIncZxWYyYk5fN2dzsLkMxUOx+iyojrtxbZAbTlyNWK8J0YC4MRHx0fFOF4hXodenv8MlA1iNtnyIY97wvWjLwutokdzHzln0KgsRwaLFK+zF/P9nvk8ygWoAAnluaytvMupvUTWisoFg6PV9nUPJEC03uWZPbqn9HYG/dCiR1dhjFTX0zG1zSjL0uTBcmNwKK06XjnovzTw/vkg+t+nRK4LkfI8/3k3KU6Ndloe1RfbNa3zMHOh3EZJeXUdHdbs4cRc/fwhOS/DcpGc0ySU4xRTz0I3IpuZZc6+Wcz0O8TfLXyHHiJx+GOg==
  template:
    metadata:
      creationTimestamp: null
      name: yelp-camp-ground
      namespace: three-tier
    type: Opaque

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
  namespace: three-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: sriram8788/campground:10
          ports:
            - containerPort: 3500
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-ground
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-ground
                  key: CLOUDINARY_KEY
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-ground
                  key: CLOUDINARY_SECRET
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-ground
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-ground
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-ground
                  key: SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
  namespace: three-tier
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3500
      targetPort: 3500
  type: LoadBalancer
